addpath('../metismex-master/build/src', ...
        '../metismex-master/build/mex');
addpath('ddm', ...
        'ddm_time', ... 
        'eigen', ...
        'fdm', ...
        'fem', ...
        'meshless', ...
        'multigrid', ...
        'newton_krylov', ...
        'nystrom', ...
        'pipelined_krylov', ...
        'spai');