clear;clc;close all;
n=999; % use odd number of points (simpson 1/3)
% n=n+(1-mod(n,2));
f=@(x) (exp(x)+x.^2);
a=0;
b=1;
h=(b-a)/(n-1);
x=a:h:b;
t=0:h:(b-a);
Dt=(h/2)*spdiags([1; 2*ones(n-2,1); 1],0,n,n);
d=ones(n,1);
d(2:2:n-1)=4;
d(3:2:n-1)=2;
Ds=(h/3)*spdiags(d,0,n,n);
K=(x.^2)'*t;
I=speye(n);
At=I+K*Dt;
As=I+K*Ds;
b=f(x)';
% ut=At\b;
% us=As\b;
tol=1e-10;
ut=bicgstab(At,b,tol,100);
us=bicgstab(As,b,tol,100);
% ut=gmres(At,b,20,tol,5);
% us=gmres(As,b,20,tol,5);
plot(1:n,ut,'bo',1:n,us,'r*');
exact=exp(x)';
err_t=norm(exact-ut)%/norm(ut)
err_s=norm(exact-us)%/norm(us)